[metadata]
firstName = "Herschel"
lastName = "Pawar"
headerQuote = [
    "Enthusiastic learner, curious about everything.",
    "Looking forward to work on projects that make a difference",
]
awesomeColor = "red"
profilePhoto = "/src/photo.png"
varLanguage = ""
varEntrySocietyFirst = false
varDisplayLogo = true
cvFooter = "Curriculum vitae"
letterFooter = "Cover Letter"
[metadata.personalInfo]
github = "pawarherschel"
phone = "+91 83107 83472"
email = "pawarherschel@sakurakat.systems"
linkedin = "pawarherschel"
homepage = "sakurakat.systems"
orcid = "0009-0003-3218-801X"

#--------------------------------------------------------------------------------

# [[certificate]]
# date = ""
# title = ""
# issuer = ""

[[certificate]]

#--------------------------------------------------------------------------------

# [[education]]
# title = ""
# society = ""
# date = ""
# location = ""
# logo = "src/logos/"
# [[education.description]]

[[education]]
title = "Bachelors of Engineering in Information Technology"
society = "University of Mumbai"
date = "2020 - 2024"
location = "MGM College of Engineering and Technology, Kamothe, Navi Mumbai, India"
logo = "src/logos/mgmcet.jpeg"
description = []

[[education]]
title = "Higher Secondary School Certificate"
society = "Central Board of Secondary Education"
date = "2018 - 2020"
location = "Greenfingers Global School, Kharghar, Navi Mumbai, India"
logo = "src/logos/gfgs.png"
description = []

[[education]]
title = "Secondary School Certificate"
society = "Indian Certificate of Secondary Education"
date = "2008 - 2018"
location = "Sanjivani International School, Kharghar, Navi Mumbai, India"
logo = "src/logos/sis.png"
description = []

#--------------------------------------------------------------------------------

# [[professional]]
# title = ""
# society = ""
# logo = ""
# date = ""
# location = ""
# description = []

# [[professional]]

#--------------------------------------------------------------------------------

# [[projects]]
# title = ""
# society = ""
# date = ""
# location = ""
# description = []

[[projects]]
title = "VRCX Insights"
society = "Personal Project"
date = "2023 - Present"
location.github = "pawarherschel/vrcx-insights"
description = [
    "A simple program to find out the various friend circles which might exist via the data collected by VRCX",
    "Written in Rust, it uses the SQLite database created by VRCX to find out the friend circles",
]

[[projects]]
title = "Booth Archiver"
society = "Personal Project"
date = "2023 - Present"
location.github = "pawarherschel/booth_archiver"
description = [
    "A simple CLI tool to archive the contents of your booth wishlist",
    "Written in Rust, it scrapes the Booth website and downloads images for each item",
    "It then converts the data into an Excel spreadsheet and writes markdown files for each item",
]

[[projects]]
title = "Tachiyomi Backup to AniList"
society = "Personal Project"
date = "2024 - Present"
location.github = "pawarherschel/tachiyomi-backup-to-anilist"
description = [
    "A simple CLI tool to sync manga from Tachiyomi backup to AniList",
    "Tachiyomi's backup is a gzipped protobuf file, this tool reads the file and syncs the manga to AniList",
]

[[projects]]
title = "Stock Crasher"
society = "Personal Project"
date = "2023"
location.github = "SakuraKat/stock-crasher"
description = [
    "A silly cli tool to show the current price of a stock in VRChat using OSC",
    "It gets the stock price from Yahoo Finance and sends it to VRChat via the OSC protocol",
]

[[projects]]
title = "Cosmos Conquerors (GMTK2023)"
society = "GMTK2023 Game Jam"
date = "2023"
location.github = "pawarherschel/GMTK2023"
description = [
    "A game made for the GMTK Game Jam 2023, the theme was 'Roles Reverse'.",
    "This is a simple game where the roles from the game Space Invaders are reversed.",
    "Available on itch.io (https://pawarherschel.itch.io/cosmos-conquerors)",
]

[[projects]]
title = "Various Simple Games made in Godot"
society = "Personal Projects"
date = "2021"
location.github = "SakuraKat"
description = [
    "Various simple games made in Godot as Proof of Concepts",
    "Jump Cat, Meme Invaders, Maze Generation, Pop The Lock, Magical Marshmellow, Game Of Life, Minesweeper, Pong, Snake",
]

#--------------------------------------------------------------------------------

# [[publication]]
# title = ""
# society = ""
# date = ""
# location = ""
# description = []

[[publications]]
title = "Social Circle Mining in VRChat Through Activity Frequencies Using Fuzzy DBSCAN"
society = "(ongoing)"
date = "2023 - Present"
location.github = "pawarherschel/vrcx-insights"
description = [
    "Ongoing research project to find out the various friend circles which might exist via the data collected by VRCX",
    "Uses Fuzzy DBSCAN to cluster users based on their activity frequencies",
]

#--------------------------------------------------------------------------------

[bibliography]
bibPath = ""
refStyle = "apa"

#--------------------------------------------------------------------------------

# [[skills]]
# type = ""
# info = []

[[skills]]
type = "Languages"
info = ["English", "Hindi", "Marathi"]

[[skills]]
type = "Projects"
info = ["Rust", "GDScript"]

[[skills]]
type = "Libraries"
info = ["prost", "Clap", "Rayon", "ureq", "SQLx"]

[[skills]]
type = "Personal Interests"
info = ["Manga & Scanlation", "VRChat", "Game Development"]

[[skills]]
type = "Software Tools"
info = ["Git", "Photoshop", "Godot", "Microsoft Word"]

[[skills]]
type = "Knowledge Areas"
info = ["Docker", "Cloudflare", "Ansible", "Linux", "Power Automate"]
