name: Check PDF Compilation

on:
  push: {}
  pull_request: {}

jobs:
  build:
    name: compile-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Typst
        uses: yusancky/setup-typst@v2.0.1
        id: setup-typst
        with:
          version: 'latest'

      - run: typst compile ./src/cv.typ ./output/CV.pdf --font-path ./src/fonts/ --root "."
      - run: typst compile ./src/letter.typ ./output/Letter.pdf  --font-path ./src/fonts/ --root "."

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output/*.pdf
          if-no-files-found: error

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            *.pdf
